version: '3.8'

services:

  db:
    image: mysql:8.0.26
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    command: [ "--log-bin", "--server-id=1" ]
